import './globals.css';
import Navbar from './Navbar';

export const metadata = {
  title: 'RSEF',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="hk">
      <body>
        <Navbar />

        {children}
      </body>
    </html>
  );
}
